pipeline{
	agent any
	
	stages {
		stage('Compile Stage') {
			steps {
				withMaven(maven : 'local_maven') {
					sh 'mvn clean compile'
				}
			}
	 }
	 	stage ('Testing Stage') {
	 		steps {
				withMaven(maven : 'local_maven') {
					sh 'mvn test'
				}
			}
	 	}
	 
		stage ('Deployment Stage') {
	 		steps {
				withMaven(maven : 'local_maven') {
					sh 'mvn deploy'
				}
			}
	 	}
	}
}